# Generated by Django 2.2.1 on 2019-05-24 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.TextField(blank=True, help_text='HT__DATA', null=True, verbose_name='VN__DATA')),
                ('user', models.ForeignKey(help_text='HT__USER', on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL, verbose_name='VN__USER')),
            ],
            options={
                'verbose_name': 'VN__IMAGE',
                'verbose_name_plural': 'VN__IMAGES',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='HT__TITLE', max_length=150, verbose_name='VN__TITLE')),
                ('owner', models.ForeignKey(help_text='HT__OWNER', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL, verbose_name='VN__OWNER')),
            ],
            options={
                'verbose_name': 'VN__TOPIC',
                'verbose_name_plural': 'VN__TOPICS',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TopicMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, help_text='HT__CONTENT', null=True, verbose_name='VN__CONTENT')),
                ('images', models.ManyToManyField(blank=True, help_text='HT__IMAGE', related_name='topic_messages', to='topics.Image', verbose_name='VN__IMAGE')),
                ('topic', models.ForeignKey(help_text='HT__TOPIC', on_delete=django.db.models.deletion.CASCADE, related_name='topic_messages', to='topics.Topic', verbose_name='VN__TOPIC')),
                ('user', models.ForeignKey(help_text='HT__USER', on_delete=django.db.models.deletion.CASCADE, related_name='topic_messages', to=settings.AUTH_USER_MODEL, verbose_name='VN__USER')),
            ],
            options={
                'verbose_name': 'VN__TOPIC_MESSAGE',
                'verbose_name_plural': 'VN__TOPIC_MESSAGES',
                'ordering': ('-created_at',),
            },
        ),
    ]
