# Generated by Django 2.2.1 on 2019-06-05 13:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topics', '0003_topicmessageread'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topicmessageread',
            unique_together={('message', 'user')},
        ),
    ]
