# Generated by Django 2.2.1 on 2019-06-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_auto_20190605_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='data',
        ),
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.ImageField(blank=True, help_text='HT__URL', null=True, upload_to='', verbose_name='VN__URL'),
        ),
    ]
